cc_library(
    name = 'weighted_random_selection',
    srcs = 'wrs.cpp'
)

cc_binary(                                                                                             
    name = 'wrs_test',                                                                                     
    srcs = ["wrs_test.cpp"],
    deps = ["//weighted_random_selection:weighted_random_selection"]
)