/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 1;
extern const char* const kSvnInfo[1] = {"https://github.com/isfull/mohosojo.git\n\
* master\n\
commit ab6885ee9504a0405077a8697575ab4e5a6241ea\n\
Author: Cheng  Chuan <ci_azure@163.com>\n\
Date:   Tue Sep 20 11:20:23 2016 +0800\n\
\n\
    Initial commit\n\
"};
extern const char kBuildType[] = "debug";
extern const char kBuildTime[] = "Tue Sep 20 13:25:59 2016";
extern const char kBuilderName[] = "allen";
extern const char kHostName[] = "6300-130906-PC";
extern const char kCompiler[] = "GCC 4.8.4-2ubuntu1~14.04.3)";
}}
